export const buttonClass = {
  base: {
    initial: {
      display: 'inline-block',
      verticalAlign: 'middle',
      userSelect: 'none',
      fontFamily: 'font-sans',
      fontWeight: 'font-bold',
      textAlign: 'center',
      textTransform: 'uppercase',
      transition: 'transition-all',
    },
    fullWidth: {
      display: 'block',
      width: 'w-full',
    },
  },
  sizes: {
    sm: {
      fontSize: 'text-xs',
      py: 'py-2',
      px: 'px-4',
      borderRadius: 'rounded-lg',
    },
    md: {
      fontSize: 'text-xs',
      py: 'py-3',
      px: 'px-6',
      borderRadius: 'rounded-lg',
    },
    lg: {
      fontSize: 'text-sm',
      py: 'py-3.5',
      px: 'px-7',
      borderRadius: 'rounded-lg',
    },
  },
  variants: {
    filled: {
      primary: {
        backgroud: 'bg-primary-500',
        color: 'text-white',
        shadow: 'shadow-md shadow-primary-500/20',
        hover: 'hover:shadow-lg hover:shadow-primary-500/40',
        focus: 'focus:opacity-[0.85] focus:shadow-none',
        active: 'active:opacity-[0.85] active:shadow-none',
      },
      secondary: {
        backgroud: 'bg-secondary-500',
        color: 'text-white',
        shadow: 'shadow-md shadow-secondary-500/20',
        hover: 'hover:shadow-lg hover:shadow-secondary-500/40',
        focus: 'focus:opacity-[0.85] focus:shadow-none',
        active: 'active:opacity-[0.85] active:shadow-none',
      },
      info: {
        backgroud: 'bg-info-500',
        color: 'text-white',
        shadow: 'shadow-md shadow-info-500/20',
        hover: 'hover:shadow-lg hover:shadow-info-500/40',
        focus: 'focus:opacity-[0.85] focus:shadow-none',
        active: 'active:opacity-[0.85] active:shadow-none',
      },
      warning: {
        backgroud: 'bg-warning-500',
        color: 'text-white',
        shadow: 'shadow-md shadow-warning-500/20',
        hover: 'hover:shadow-lg hover:shadow-warning-500/40',
        focus: 'focus:opacity-[0.85] focus:shadow-none',
        active: 'active:opacity-[0.85] active:shadow-none',
      },
      danger: {
        backgroud: 'bg-danger-500',
        color: 'text-white',
        shadow: 'shadow-md shadow-danger-500/20',
        hover: 'hover:shadow-lg hover:shadow-danger-500/40',
        focus: 'focus:opacity-[0.85] focus:shadow-none',
        active: 'active:opacity-[0.85] active:shadow-none',
      },
      success: {
        backgroud: 'bg-success-500',
        color: 'text-white',
        shadow: 'shadow-md shadow-success-500/20',
        hover: 'hover:shadow-lg hover:shadow-success-500/40',
        focus: 'focus:opacity-[0.85] focus:shadow-none',
        active: 'active:opacity-[0.85] active:shadow-none',
      },
      dark: {
        backgroud: 'bg-dark-500',
        color: 'text-white',
        shadow: 'shadow-md shadow-dark-500/20',
        hover: 'hover:shadow-lg hover:shadow-dark-500/40',
        focus: 'focus:opacity-[0.85] focus:shadow-none',
        active: 'active:opacity-[0.85] active:shadow-none',
      },
      light: {
        backgroud: 'bg-light-500',
        color: 'text-white',
        shadow: 'shadow-md shadow-light-500/20',
        hover: 'hover:shadow-lg hover:shadow-light-500/40',
        focus: 'focus:opacity-[0.85] focus:shadow-none',
        active: 'active:opacity-[0.85] active:shadow-none',
      },
    },
    gradient: {
      primary: {
        backgroud: 'bg-gradient-to-tr from-primary-600 to-primary-400',
        color: 'text-white',
        shadow: 'shadow-md shadow-primary-500/20',
        hover: 'hover:shadow-lg hover:shadow-primary-500/40',
        active: 'active:opacity-[0.85]',
      },
      secondary: {
        backgroud: 'bg-gradient-to-tr from-secondary-600 to-secondary-400',
        color: 'text-white',
        shadow: 'shadow-md shadow-secondary-500/20',
        hover: 'hover:shadow-lg hover:shadow-secondary-500/40',
        active: 'active:opacity-[0.85]',
      },
      info: {
        backgroud: 'bg-gradient-to-tr from-info-600 to-info-400',
        color: 'text-white',
        shadow: 'shadow-md shadow-info-500/20',
        hover: 'hover:shadow-lg hover:shadow-info-500/40',
        active: 'active:opacity-[0.85]',
      },
      warning: {
        backgroud: 'bg-gradient-to-tr from-warning-600 to-warning-400',
        color: 'text-white',
        shadow: 'shadow-md shadow-warning-500/20',
        hover: 'hover:shadow-lg hover:shadow-warning-500/40',
        active: 'active:opacity-[0.85]',
      },
      danger: {
        backgroud: 'bg-gradient-to-tr from-danger-600 to-danger-400',
        color: 'text-white',
        shadow: 'shadow-md shadow-danger-500/20',
        hover: 'hover:shadow-lg hover:shadow-danger-500/40',
        active: 'active:opacity-[0.85]',
      },
      success: {
        backgroud: 'bg-gradient-to-tr from-success-600 to-success-400',
        color: 'text-white',
        shadow: 'shadow-md shadow-success-500/20',
        hover: 'hover:shadow-lg hover:shadow-success-500/40',
        active: 'active:opacity-[0.85]',
      },
      dark: {
        backgroud: 'bg-gradient-to-tr from-dark-600 to-dark-400',
        color: 'text-white',
        shadow: 'shadow-md shadow-dark-500/20',
        hover: 'hover:shadow-lg hover:shadow-dark-500/40',
        active: 'active:opacity-[0.85]',
      },
      light: {
        backgroud: 'bg-gradient-to-tr from-light-600 to-light-400',
        color: 'text-white',
        shadow: 'shadow-md shadow-light-500/20',
        hover: 'hover:shadow-lg hover:shadow-light-500/40',
        active: 'active:opacity-[0.85]',
      },
    },
    outlined: {
      primary: {
        backgroud: 'border border-primary-500',
        color: 'text-primary-500',
        hover: 'hover:opacity-75',
        focus: 'focus:ring focus:ring-primary-200',
        active: 'active:opacity-[0.85]',
      },
      secondary: {
        backgroud: 'border border-secondary-500',
        color: 'text-secondary-500',
        hover: 'hover:opacity-75',
        focus: 'focus:ring focus:ring-secondary-200',
        active: 'active:opacity-[0.85]',
      },
      info: {
        backgroud: 'border border-info-500',
        color: 'text-info-500',
        hover: 'hover:opacity-75',
        focus: 'focus:ring focus:ring-info-200',
        active: 'active:opacity-[0.85]',
      },
      warning: {
        backgroud: 'border border-warning-500',
        color: 'text-warning-500',
        hover: 'hover:opacity-75',
        focus: 'focus:ring focus:ring-warning-200',
        active: 'active:opacity-[0.85]',
      },
      danger: {
        backgroud: 'border border-danger-500',
        color: 'text-danger-500',
        hover: 'hover:opacity-75',
        focus: 'focus:ring focus:ring-danger-200',
        active: 'active:opacity-[0.85]',
      },
      success: {
        backgroud: 'border border-success-500',
        color: 'text-success-500',
        hover: 'hover:opacity-75',
        focus: 'focus:ring focus:ring-success-200',
        active: 'active:opacity-[0.85]',
      },
      dark: {
        backgroud: 'border border-dark-500',
        color: 'text-dark-500',
        hover: 'hover:opacity-75',
        focus: 'focus:ring focus:ring-dark-200',
        active: 'active:opacity-[0.85]',
      },
      light: {
        backgroud: 'border border-light-500',
        color: 'text-light-500',
        hover: 'hover:opacity-75',
        focus: 'focus:ring focus:ring-light-200',
        active: 'active:opacity-[0.85]',
      },
    },
    text: {
      primary: {
        color: 'text-primary-500',
        hover: 'hover:bg-primary-500/10',
        active: 'active:bg-primary-500/30',
      },
      secondary: {
        color: 'text-secondary-500',
        hover: 'hover:bg-secondary-500/10',
        active: 'active:bg-secondary-500/30',
      },
      info: {
        color: 'text-info-500',
        hover: 'hover:bg-info-500/10',
        active: 'active:bg-info-500/30',
      },
      warning: {
        color: 'text-warning-500',
        hover: 'hover:bg-warning-500/10',
        active: 'active:bg-warning-500/30',
      },
      danger: {
        color: 'text-danger-500',
        hover: 'hover:bg-danger-500/10',
        active: 'active:bg-danger-500/30',
      },
      success: {
        color: 'text-success-500',
        hover: 'hover:bg-success-500/10',
        active: 'active:bg-success-500/30',
      },
      dark: {
        color: 'text-dark-500',
        hover: 'hover:bg-dark-500/10',
        active: 'active:bg-dark-500/30',
      },
      light: {
        color: 'text-light-500',
        hover: 'hover:bg-light-500/10',
        active: 'active:bg-light-500/30',
      },
    },
  },
};
export default buttonClass;
